trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      docker run --rm -d -p 9200:9200 --name=elasticsearch -e "xpack.security.enabled=false" -e "discovery.type=single-node" -e "ES_JAVA_OPTS=-Xms1024m -Xmx1024m" elasticsearch:7.17.6 && \
      sleep 10
    displayName: 'run elasticsearch container'

  - script: |
      docker run --rm -d -p 5432:5432 --name=elastic-test -e "POSTGRES_DB=${POSTGRES_DB}" -e "POSTGRES_USER=${POSTGRES_USER}" -e "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" postgres:14.5 && \
      sleep 10
    displayName: 'run postgres container'

  - task: UseDotNet@2
    displayName: 'install .net sdk 6.x'
    inputs:
      version: 6.x
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      $(Agent.ToolsDirectory)/dotnet/dotnet test --logger trx --results-directory $(Agent.TempDirectory) --verbosity d
    displayName: 'run tests'

  - task: PublishTestResults@2
    displayName: 'publish test results'
    inputs:
      testResultsFiles: '$(Agent.TempDirectory)/*.trx'
      testResultsFormat: VSTest
      publishRunAttachments: true