version: '3.4'

services:
  elasticsearch-test:
    container_name: elasticsearch-test
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    ports:
      - 19200:9200
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"

  postgres-test:
    container_name: postgres-test
    image: postgres:14.5
    environment:
      POSTGRES_DB: onlinesales-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"